services:
  postgres:
    image: postgres:15
    platform: linux/arm64
    container_name: auth_service_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: guimox
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: auth_service_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}

  app:
    image: ghcr.io/${GITHUB_REPOSITORY}/${DOCKER_CONTAINER_NAME}:v1.0.0
    container_name: ${DOCKER_CONTAINER_NAME}
    environment:
      - DB_URL=${DB_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_PORT=${APP_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL=${RESEND_EMAIL}
    ports:
      - "8088:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend: