spring:
  oauth2:
    client-id: id
    client-secret: secret
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-db
    username: postgres
    password: secret123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
app:
  jwt:
    secret: jwt-secret
    access-token-expiration-ms: 86400000  # 24 hours
    refresh-token-expiration-ms: 86400000  # 24 hours
    token-version-header: X-Token-Version
  resend:
    api-key: resend-api-key
    from-email: email
server:
  port: 8087
security:
  filter-dispatch-types: REQUEST
logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth: DEBUG