spring:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  datasource:
    url: ${DB_URL}
    username: guimox
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 86400000  # 24 hours
    refresh-token-expiration-ms: 86400000  # 24 hours
    token-version-header: X-Token-Version
  resend:
    api-key: ${RESEND_API_KEY}
    from-email: ${RESEND_EMAIL}
server:
  port: 8087
security:
  filter-dispatch-types: REQUEST
logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth: DEBUG