name: Build and Deploy Spring API

on:
  push:
    branches:
      - trying-cicd

jobs:
  build-deploy:
    name: Build and Deploy Spring API
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Build the App
        run: mvn clean package -Pprd -DskipTests --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Push Multi-Architecture Docker Image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create app directory on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ ! -d "/home/${{ secrets.VPS_USERNAME }}/apps/guimox-auth" ]; then
              mkdir -p /home/${{ secrets.VPS_USERNAME }}/apps/guimox-auth
            fi

      - name: Upload docker-compose-prd.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "docker-compose-prd.yml"
          target: "/home/${{ secrets.VPS_USERNAME }}/apps/guimox-auth/"

      - name: Create .env file on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/apps/guimox-auth
            cat > .env << EOF
            # Database Configuration
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_URL=${{ secrets.DB_URL }}
            
            # Redis Configuration
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            
            # Application Configuration
            APP_PORT=${{ secrets.APP_PORT }}
            
            # Authentication Secrets
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            
            # Email Configuration
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            RESEND_EMAIL=${{ secrets.RESEND_EMAIL }}
            
            # Docker Configuration
            DOCKER_CONTAINER_NAME=${{ secrets.DOCKER_CONTAINER_NAME }}
            GITHUB_REPOSITORY=${{ github.repository }}
            EOF
            chmod 600 .env

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            cd /home/${{ secrets.VPS_USERNAME }}/apps/guimox-auth
            docker pull ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0
            docker compose -f docker-compose-prd.yml down --remove-orphans
            docker compose -f docker-compose-prd.yml up -d --force-recreate --remove-orphans
            docker image prune -f
